modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory

[[mods]] #mandatory
	modId="xpbook" #mandatory
	version="${version}" #mandatory
	displayName="XP Tome" #mandatory
	description='''Adds a book that can store a configurable amount of XP.''' #mandatory
	issueTrackerURL="https://github.com/bl4ckscor3/XP-Tome/issues"
	displayURL="http://minecraft.curseforge.com/projects/xp-tome"
	authors="bl4ckscor3"

[[dependencies.xpbook]]
    modId="forge"
    mandatory=true
    versionRange="[31.2.10,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.xpbook]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15,1.16)"
    ordering="NONE"
    side="BOTH"