modLoader="javafml"
loaderVersion="[46,)"
license="MIT https://github.com/bl4ckscor3/XP-Tome/blob/1.20/LICENSE"
issueTrackerURL="https://github.com/bl4ckscor3/XP-Tome/issues"

[[mods]]
	modId="xpbook"
	version="${file.jarVersion}"
	displayName="XP Tome"
	description='''Adds a book that can store a configurable amount of XP.'''
	displayURL="https://minecraft.curseforge.com/projects/xp-tome"
	authors="bl4ckscor3"

[[dependencies.xpbook]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.xpbook]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"