modLoader="javafml"
loaderVersion="[41,)"
license="GNU GPL v3.0 https://github.com/bl4ckscor3/XP-Tome/blob/1.19/LICENSE"
issueTrackerURL="https://github.com/bl4ckscor3/XP-Tome/issues"

[[mods]]
	modId="xpbook"
	version="${file.jarVersion}"
	displayName="XP Tome"
	description='''Adds a book that can store a configurable amount of XP.'''
	displayURL="http://minecraft.curseforge.com/projects/xp-tome"
	authors="bl4ckscor3"

[[dependencies.xpbook]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.xpbook]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"