modLoader="javafml" #mandatory
loaderVersion="[33,)" #mandatory
license="GNU GPL v3.0 https://github.com/bl4ckscor3/XP-Tome/blob/1.16/LICENSE"
issueTrackerURL="https://github.com/bl4ckscor3/XP-Tome/issues"
displayURL="http://minecraft.curseforge.com/projects/xp-tome"
authors="bl4ckscor3"

[[mods]] #mandatory
modId="xpbook" #mandatory
version="v1.1.6" #mandatory
displayName="XP Tome" #mandatory
description='''Adds a book that can store a limited amount of XP.''' #mandatory

[[dependencies.xpbook]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.xpbook]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="BOTH"